services:

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - product-service
      - order-service

  product-service:
    build: ./product-service
    container_name: product-container
    ports:
      - "5002:5002"

  order-service:
    build: ./order-service
    container_name: order-container
    ports:
      - "5001:5001"
    depends_on:
      - product-service